global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Prisma Cloud scrape configuration.
scrape_configs:

  - job_name: 'twistlock'
    static_configs:
    - targets: ['twistlock_console:8083']
    metrics_path: /api/v1/metrics
    basic_auth:
      username: '<PRISMA_USER>'
      password: '<PRISMA_PASSWORD>'
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'drone'
    bearer_token: <DRONE_METRICS_API_TOKEN>
    static_configs:
    - targets: ['drone:8000']
    
  - job_name: 'gitea'
    bearer_token: <GITEA_METRICS_API_TOKEN>
    static_configs:
    - targets: ['gitea:3000']
